- qubesappmenus/__init__.py
- qubesappmenus/receive.py
The main fix is forcing map object to list, for 'in' operator to work.
But while at it, simplify file names handling a little.
Fixes QubesOS/qubes-issues#2895
> Fix application icons generation

- qubesappmenusext/__init__.py
1. Rename is no longer supported
2. Use coroutine handlers (where allowed) - this will avoid race
condition between create and remove called quickly one after another
(like in integration tests).
Fixes QubesOS/qubes-issues#2918
> appmenus: convert to coroutine event handlers, remove rename handling

- appmenus-files/qubes-start.desktop
The qvm-start command in Qubes OS 4.0 doesn't have the --tray argument
anymore.
> appmenus: fix compatibility with Qubes OS 4.0

- qubesappmenus/__init__.py
After disabling this in dom0 and adding a VM or related changes
I see the menu options update (with a couple of seconds delay) as
expected.
This seems to be fixed upstream.
> Remove unneeded warning/removal of icon-cache for KDE desktops

- qubesappmenusext/__init__.py
I'm not sure that generic domain-feature-{set,delete} handlers checking the feature argument instead of specific domain-feature-{set,delete}:featurename events is the way to go - it seems a little inconsistent with other event handling. However, this is what the tests expect, and there's no authoritative documentation about which way it *should* be.
Discussion here: https://groups.google.com/d/topic/qubes-devel/tL756bswGpg/discussion
> Regen appmenus on relevant feature changes

- doc/tools/qvm-appmenus.rst
- qubesappmenus/__init__.py
Adding the optional --file-field parameter. It changes to output format
to '|'-separated one, and outputs not only file name and app name, but
also whatever fields from the file the user has requested. Used by
GUI VM settings.
references QubesOS/qubes-issues#5076
> Added handling for more file fields in GetAppmenus

- qubesappmenus/__init__.py
Designed to be used to replace a VM's template for the purposes of
--get-available; to be used in Qube Settings when VM template is changed.
references QubesOS/qubes-issues#5796
> Added a --template option to qvm-appmenus

- qubesappmenus/receive.py
Spaces are now allowed around '=' in .desktop files and should be stripped
correctly.
fixes QubesOS/qubes-issues#5692
> Fixed handling of spaces in qvm-sync-appmenus

- .gitignore
- Makefile
- debian/control
> debian: fix dependency names

- qubesappmenus/qubes-vm-settings.desktop.template
- rpm_spec/desktop-linux-common.spec.in
Appropriate menu entries will now show only when qubesmanager is installed.
> Removed dependency on qubesmanager

- qubesappmenus/receive.py
Also added an option to enforce running as root, if someone really
really wants it (not recommended).
fixes QubesOS/qubes-issues#4956
> Warn user against running qvm-sync-appmenus as root

- qubesappmenus/__init__.py
First, check the feature on the VM itself only - no sense for checking
it on the template. But then, handle also the case when Admin API call
was refused.
QubesOS/qubes-issues#833
> appmenus: make it more robust about appmenus-dispvm feature access

- qubesappmenus/receive.py
The plus sign is a valid character for these fields. Righ now,
qvm-sync-appmenus discards entries containing plus signs. This change
corrects that.
> Accept "+" as part of the Name, GenericName, and Comment fields on qvm-sync-appmenus

- qubesappmenus/__init__.py
- qubesappmenus/tests.py
- qubesappmenusext/__init__.py
Otherwise, we will try to start a DispVM based on a VM that is not a DispVM template, which cannot work.  Also block `appmenus-dispvm` from being set on a VM that is not a DispVM template.
Fixes QubesOS/qubes-issues#4636
Fixes QubesOS/qubes-issues#6683
> Ignore appmenus-dispvm unless template_for_dispvms=True

- qubesappmenusext/__init__.py
It will be copied from Disposable Template, but should be just ignored.
This fixes:
AttributeError: 'DispVM' object has no attribute 'template_for_dispvms'
> Don't crash on setting 'appmenus-dispvm' feature on DispVM itself

- .gitlab-ci.yml
- ci/codecov-wrapper
Since our CI doesn't re-use github's merge commits anymore, codecov
needs to be helped to get the right commit ID.
> ci: use a wrapper to properly mark coverage data

- qubesappmenus/__init__.py
- qubesappmenus/tests.py
Simple new function and associated tests, to be
complementary to --set-default-whitelist.
> Add a --get-default-whitelist to qvm-appmenus

- qubesappmenus/__init__.py
Fixes [qubes-issues#7705](https://github.com/QubesOS/qubes-issues/issues/7705)
Currently appmenus removal on dispvm templates errors out:
```
xdg-desktop-menu: desktop-file argument missing
Try 'xdg-desktop-menu --help' for more information.
Problem removing appmenus for test-dvm
```
This appears to be coming from an ill-formed call to `xdg-desktop-menu`, which happens because `_is_old_path` is not correctly checked for dispvm directory names.
> Fix `_is_old_path` for dispvm directory names

- qubesappmenus/__init__.py
Instead of crashing, will just skip them.
fixes QubesOS/qubes-issues#7668
> Don't crash qvm-appmenus on erroneous .desktop files

- qubes-menus/menus/qubes-applications.menu
obsoleted by new global config in https://github.com/QubesOS/qubes-desktop-linux-manager
fixes QubesOS/qubes-issues#8201
fixes QubesOS/qubes-issues#8200
> Remove old global settings from menu

- qubesappmenus/__init__.py
- qubesappmenus/qubes-vm-settings.desktop.template
- qubesappmenus/qubes.SyncAppMenus.policy
- qubesappmenus/receive.py
- qubesappmenus/tests.py
- qubesappmenus/tests_integ.py
As they are a delimiter, they must be escaped to prevent collisions.
> Handle periods in qube names

- Makefile
- debian/qubes-desktop-linux-common.install
- qubesappmenus/__init__.py
- qubesappmenus/qubes.RemoveAppMenusFor
- qubesappmenus/qubes.UpdateAppMenusFor
- qubesappmenusext/__init__.py
- rpm_spec/desktop-linux-common.spec.in
Fixes QubesOS/qubes-issues#8494
Fixes QubesOS/qubes-issues#8528
QubesOS/qubes-issues#5804
> A bunch of fixes to appmenus handling with GUI VM

- qubesappmenus/tests.py
Applications list depend on filesystem listing order which isn't
deterministic. Sort data before comparing. Do not use set(), the test
should fail if there are duplicates.
> tests: sort applications list before comparing

- qubesappmenusext/__init__.py
Retrieve results of background tasks (log errors), and also ensure they are
completed before removing a qube.
> Improve background tasks handling

- qubesappmenus/tests_integ.py
> Update (tests) for F41 dom0

- qubesappmenus/__init__.py
- qubesappmenus/receive.py
- qubesappmenus/tests.py
Improved version of #63 , this time with backwards compatibility.
>  Remove deprecated pkg_resources, replace with importlib

- qubesappmenus/__init__.py
- qubesappmenus/receive.py
`qvm-sync-appmenus` called with a non-running qube now fails with a user-friendly error message. See QubesOS/qubes-issues#9836
Another minor fix is provided when calling `qvm-appmenus ... VMNAME` where `VMNAME` doesn't exist.
> Catching exceptions with `qvm-appmenus` and `qvm-sync-appmenus`
